// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package db

import (
	"context"
)

const insertSessions = `-- name: InsertSessions :one
INSERT INTO sessions (ua, ip, user_id, token, expires, created, updated)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertSessionsParams struct {
	UA      string
	IP      string
	UserID  int64
	Token   string
	Expires int64
	Created int64
	Updated int64
}

func (q *Queries) InsertSessions(ctx context.Context, arg InsertSessionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSessions,
		arg.UA,
		arg.IP,
		arg.UserID,
		arg.Token,
		arg.Expires,
		arg.Created,
		arg.Updated,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
