// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID      int64
	UA      string
	IP      string
	UserID  int64
	Token   string
	Created int64
	Expires int64
	Updated int64
}

type User struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
}

type Workspace struct {
	ID        pgtype.UUID
	Name      string
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	JoinedAt    pgtype.Timestamptz
}
